In [12]:
import numpy as np
# import torch

class NeuralNetwork:
    def __init__(self, layer_sizes):
        # layer_sizes = (2,3,5,2)
        w_shapes = [(a,b) for a,b in zip(layer_sizes[1:], layer_sizes[:-1])]
        self.weights = [np.random.standard_normal(s) for s in w_shapes]
        self.biases = [np.zeros((s,1)) for s in layer_sizes[1:]]
        # print(w_shapes)
        # for w in weights:
        #     print(w,'\n')
    
    def predict(sef, a):
        for w,b in zip(self.weights, self.biases):
            a = self.activation(np.matmul(w,a) + b)
        return a 

    @staticmethod
    def activation(x):
        return 1/(1+np.exp(-x))





# a = np.array([1,2,3,4])
# print(a)

[(3, 2), (5, 3), (2, 5)]
[[ 0.40425649 -0.08117213]
 [-1.12290401 -0.9274153 ]
 [ 0.63931448  1.69953506]] 

[[ 0.7898331  -0.49823362 -2.16518849]
 [-1.10881432  0.24245484  1.07016432]
 [-0.10208149 -0.60321468 -0.44660791]
 [-1.73906706  0.41699235 -1.46755254]
 [-0.37821619  0.05436375 -0.23850714]] 

[[-0.36849425 -0.02648044 -0.48048505 -0.31661543  1.73264631]
 [ 0.91045986 -0.07046133  0.16684211  1.53088443  0.88331368]] 



In [9]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("vectorized version: " + str(1000*(toc-tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("for loop: " + str(1000*(toc-tic)) + "ms")

249757.42440279515
vectorized version: 10.072469711303711ms
249757.42440279812
for loop: 1280.0393104553223ms


In [12]:
np.max(a, 0)

0.999998640236792